#!/usr/bin/env python3

"""Measure WAL-upgrade correctness and WAL volume across transfer modes."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import asdict, dataclass
from pathlib import Path

from common import (
    GENERIC_TRANSFER_MODES,
    GIB,
    MIB,
    REFERENCE_TRANSFER_MODES,
    Cluster,
    PortAllocator,
    PostgresBinaries,
    UpgradeWal,
    append,
    check_binaries,
    check_free_space,
    configure_standalone,
    copy_stopped_cluster,
    directory_bytes,
    ensure_empty_work_dir,
    lsn_bytes,
    read_upgrade_wal,
    retained_wal_bytes,
    run,
    transfer_mode_option,
    write_json,
)


@dataclass(frozen=True)
class Scale:
    transfer_modes: tuple[str, ...]
    databases: int
    tables_per_database: int
    table_columns: int
    pgbench_scale: int
    pgbench_clients: int
    pgbench_threads: int
    transactions: int
    multixact_rows: int
    minimum_multixact_offsets_bytes: int
    minimum_target_multixact_bytes: int
    minimum_fixture_wal_bytes: int
    minimum_catalog_bytes: int
    minimum_dataset_bytes: int
    minimum_pg_xact_bytes: int
    minimum_upgrade_window_bytes: int
    wal_keep_gb: int
    minimum_free_gb: int
    jobs: int


def setting(value: int | None, quick: int, review: int, profile: str) -> int:
    if value is not None:
        return value
    return quick if profile == "quick" else review


def scale_from_args(args: argparse.Namespace) -> Scale:
    return Scale(
        transfer_modes=tuple(args.modes),
        databases=setting(args.databases, 2, 32, args.profile),
        tables_per_database=setting(args.tables_per_database, 16, 1024, args.profile),
        table_columns=setting(args.table_columns, 4, 16, args.profile),
        pgbench_scale=setting(args.pgbench_scale, 1, 300, args.profile),
        pgbench_clients=setting(args.pgbench_clients, 4, 64, args.profile),
        pgbench_threads=setting(args.pgbench_threads, 2, 16, args.profile),
        transactions=setting(args.transactions, 64, 6_720_000, args.profile),
        multixact_rows=setting(args.multixact_rows, 64, 6_720_000, args.profile),
        minimum_multixact_offsets_bytes=setting(
            args.minimum_multixact_offsets_mib, 0, 24, args.profile
        )
        * MIB,
        minimum_target_multixact_bytes=setting(
            args.minimum_target_multixact_mib, 0, 64, args.profile
        )
        * MIB,
        minimum_fixture_wal_bytes=setting(args.minimum_fixture_wal_gib, 0, 8, args.profile) * GIB,
        minimum_catalog_bytes=setting(args.minimum_catalog_mib, 0, 512, args.profile) * MIB,
        minimum_dataset_bytes=setting(args.minimum_dataset_gib, 0, 4, args.profile) * GIB,
        minimum_pg_xact_bytes=setting(args.minimum_pg_xact_mib, 0, 1, args.profile) * MIB,
        minimum_upgrade_window_bytes=setting(args.minimum_upgrade_window_gib, 0, 1, args.profile)
        * GIB,
        wal_keep_gb=setting(args.wal_keep_gb, 2, 16, args.profile),
        minimum_free_gb=setting(args.minimum_free_gb, 5, 60, args.profile),
        jobs=args.jobs,
    )


def build_catalog_fixture(cluster: Cluster, scale: Scale) -> list[str]:
    cluster.psql("CREATE DATABASE scale_template")
    columns = ", ".join(f"c{column:02d} text" for column in range(1, scale.table_columns + 1))
    batch_size = 64
    for first in range(1, scale.tables_per_database + 1, batch_size):
        last = min(first + batch_size - 1, scale.tables_per_database)
        cluster.psql(
            f"""
            SET statement_timeout = 0;
            DO $$
            BEGIN
              FOR i IN {first}..{last} LOOP
                EXECUTE format(
                  'CREATE TABLE scale_table_%s '
                  '(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, {columns})', i);
                EXECUTE format(
                  'CREATE INDEX scale_index_%s ON scale_table_%s (c01)', i, i);
              END LOOP;
            END
            $$
            """,
            database="scale_template",
        )
    cluster.psql(
        "INSERT INTO scale_table_1(c01) VALUES ('scope')",
        database="scale_template",
    )
    databases = ["scale_template"]
    for number in range(1, scale.databases):
        name = f"scale_db_{number:03d}"
        cluster.psql(f"CREATE DATABASE {name} TEMPLATE scale_template")
        databases.append(name)
    return databases


def catalog_bytes(cluster: Cluster, databases: list[str]) -> tuple[int, int]:
    local_size_query = """
        SELECT coalesce(sum(pg_total_relation_size(c.oid)), 0)
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'pg_catalog' AND c.relkind IN ('r', 'm')
          AND NOT c.relisshared
    """
    shared_size_query = """
        SELECT coalesce(sum(pg_total_relation_size(c.oid)), 0)
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'pg_catalog' AND c.relkind IN ('r', 'm')
          AND c.relisshared
    """
    count_query = """
        SELECT count(*) FROM pg_class
        WHERE relname LIKE 'scale_table_%' AND relkind = 'r'
    """
    total_bytes = int(cluster.psql(shared_size_query, database=databases[0]))
    total_tables = 0
    for database in databases:
        total_bytes += int(cluster.psql(local_size_query, database=database))
        total_tables += int(cluster.psql(count_query, database=database))
    return total_bytes, total_tables


def fixture_relation_state(cluster: Cluster, databases: list[str]) -> tuple[int, tuple[str, ...]]:
    query = """
        WITH heap_relations AS (
          SELECT c.oid
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
            AND c.relkind IN ('r', 'm')
          UNION ALL
          SELECT c.reltoastrelid
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
            AND c.relkind IN ('r', 'm') AND c.reltoastrelid <> 0
        ), physical_relations AS (
          SELECT oid FROM heap_relations
          UNION ALL
          SELECT indexrelid
          FROM pg_index
          WHERE indrelid IN (SELECT oid FROM heap_relations)
            AND indisvalid AND indisready
        ), relation_state AS (
          SELECT format(
                   '%s/%s/%s',
                   CASE WHEN c.reltablespace = 0 THEN d.dattablespace ELSE c.reltablespace END,
                   d.oid,
                   pg_relation_filenode(c.oid)
                 ) AS key,
                 pg_relation_size(c.oid, 'main') +
                 pg_relation_size(c.oid, 'fsm') +
                 pg_relation_size(c.oid, 'vm') +
                 pg_relation_size(c.oid, 'init') AS bytes
          FROM physical_relations r
          JOIN pg_class c ON c.oid = r.oid
          JOIN pg_database d ON d.datname = current_database()
          WHERE pg_relation_filenode(c.oid) IS NOT NULL
        )
        SELECT key, bytes FROM relation_state WHERE bytes > 0 ORDER BY key
    """
    total_bytes = 0
    keys: list[str] = []
    for database in ["postgres", *databases]:
        output = cluster.psql(query, database=database)
        for row in output.splitlines():
            key, relation_bytes = row.split("|")
            keys.append(key)
            total_bytes += int(relation_bytes)
    if not keys or len(keys) != len(set(keys)):
        raise AssertionError(keys)
    return total_bytes, tuple(keys)


def start_multixact_holder(cluster: Cluster, scale: Scale, output: Path) -> subprocess.Popen[str]:
    cluster.psql(
        f"""
        SET statement_timeout = 0;
        CREATE TABLE wal_upgrade_multixact
          (id integer PRIMARY KEY, touched integer NOT NULL);
        ALTER TABLE wal_upgrade_multixact SET (autovacuum_enabled = false);
        INSERT INTO wal_upgrade_multixact
          SELECT id, 0 FROM generate_series(1, {scale.multixact_rows}) id;
        CREATE SEQUENCE wal_upgrade_multixact_seq
          MINVALUE 1 MAXVALUE {scale.multixact_rows} NO CYCLE CACHE 1
        """
    )
    command = [
        str(cluster.binaries.binary("psql")),
        "-XAt",
        "-v",
        "ON_ERROR_STOP=1",
        "-h",
        "127.0.0.1",
        "-p",
        str(cluster.port),
        "-d",
        "postgres",
    ]
    print("+ " + " ".join(command), flush=True)
    process = subprocess.Popen(
        command,
        env=os.environ.copy(),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert process.stdin is not None
    assert process.stdout is not None
    process.stdin.write(
        "SET statement_timeout = 0;\n"
        "BEGIN;\n"
        "WITH locked AS MATERIALIZED ("
        "SELECT id FROM wal_upgrade_multixact ORDER BY id FOR KEY SHARE"
        ") SELECT count(*) FROM locked;\n"
        "\\echo MULTIXACT_READY\n"
    )
    process.stdin.flush()
    lines: list[str] = []
    while True:
        line = process.stdout.readline()
        if not line:
            raise RuntimeError("multixact holder exited before it was ready\n" + "".join(lines))
        lines.append(line)
        if line.strip() == "MULTIXACT_READY":
            break
    output.write_text("".join(lines))
    if str(scale.multixact_rows) not in {line.strip() for line in lines}:
        raise AssertionError(lines)
    return process


def stop_multixact_holder(process: subprocess.Popen[str], output: Path) -> None:
    assert process.stdin is not None
    assert process.stdout is not None
    process.stdin.write("COMMIT;\n\\q\n")
    process.stdin.flush()
    remaining = process.stdout.read()
    process.wait(timeout=60)
    with output.open("a") as stream:
        stream.write(remaining)
    if process.returncode != 0:
        raise RuntimeError(output.read_text())


def run_pgbench_fixture(
    cluster: Cluster,
    scale: Scale,
    initial_lsn: str,
    output_dir: Path,
) -> tuple[int, int]:
    if scale.transactions % scale.pgbench_clients != 0:
        raise ValueError("transactions must be divisible by pgbench clients")
    transactions_per_client = scale.transactions // scale.pgbench_clients
    script = output_dir / "wal_upgrade_scale.pgbench"
    script.write_text(
        f"""\\set aid random(1, {scale.pgbench_scale * 100_000})
BEGIN;
UPDATE pgbench_accounts SET abalance = abalance + 1 WHERE aid = :aid;
SELECT id FROM wal_upgrade_multixact
  WHERE id = (SELECT nextval('wal_upgrade_multixact_seq')) FOR KEY SHARE;
END;
"""
    )
    run(
        [
            cluster.binaries.binary("pgbench"),
            "-n",
            "-f",
            script,
            "-c",
            str(scale.pgbench_clients),
            "-j",
            str(scale.pgbench_threads),
            "-t",
            str(transactions_per_client),
            "-h",
            "127.0.0.1",
            "-p",
            str(cluster.port),
            "postgres",
        ],
        output=output_dir / "pgbench_transactions.log",
    )
    cluster.psql("CHECKPOINT")
    current_lsn = cluster.psql("SELECT pg_current_wal_insert_lsn()")
    return scale.transactions, lsn_bytes(current_lsn) - lsn_bytes(initial_lsn)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--old-bindir", type=Path, required=True)
    parser.add_argument("--new-bindir", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--profile", choices=("quick", "review"), default="quick")
    parser.add_argument(
        "--modes", nargs="+", choices=GENERIC_TRANSFER_MODES, default=list(GENERIC_TRANSFER_MODES)
    )
    parser.add_argument("--port-base", type=int, default=55432)
    parser.add_argument("--jobs", type=int, default=8)
    parser.add_argument("--keep-clusters", action="store_true")
    parser.add_argument("--databases", type=int)
    parser.add_argument("--tables-per-database", type=int)
    parser.add_argument("--table-columns", type=int)
    parser.add_argument("--pgbench-scale", type=int)
    parser.add_argument("--pgbench-clients", type=int)
    parser.add_argument("--pgbench-threads", type=int)
    parser.add_argument("--transactions", type=int)
    parser.add_argument("--multixact-rows", type=int)
    parser.add_argument("--minimum-multixact-offsets-mib", type=int)
    parser.add_argument("--minimum-target-multixact-mib", type=int)
    parser.add_argument("--minimum-fixture-wal-gib", type=int)
    parser.add_argument("--minimum-catalog-mib", type=int)
    parser.add_argument("--minimum-dataset-gib", type=int)
    parser.add_argument("--minimum-pg-xact-mib", type=int)
    parser.add_argument("--minimum-upgrade-window-gib", type=int)
    parser.add_argument("--wal-keep-gb", type=int)
    parser.add_argument("--minimum-free-gb", type=int)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    scale = scale_from_args(args)
    if scale.transactions != scale.multixact_rows:
        raise ValueError("transactions and multixact rows must match")
    work_dir = ensure_empty_work_dir(args.work_dir)
    check_free_space(work_dir, scale.minimum_free_gb)
    old_binaries = PostgresBinaries(args.old_bindir.resolve())
    new_binaries = PostgresBinaries(args.new_bindir.resolve())
    check_binaries(old_binaries, ("initdb", "pgbench", "pg_ctl", "psql"))
    check_binaries(new_binaries, ("pg_ctl", "pg_upgrade", "pg_waldump", "psql"))

    ports = PortAllocator(args.port_base)
    old_cluster = Cluster(work_dir / "old", old_binaries, ports.get(), "old")
    target_port = ports.get()
    socket_dir = Path(tempfile.mkdtemp(prefix="wal-upgrade-scale-"))
    upgrade_cwd = work_dir / "pg_upgrade_cwd"
    upgrade_cwd.mkdir()
    timings: dict[str, float] = {}

    try:
        old_cluster.initdb()
        configure_standalone(old_cluster, socket_dir)
        append(
            old_cluster.pgdata / "postgresql.conf",
            f"""
checkpoint_timeout = '1h'
max_connections = {max(96, scale.pgbench_clients + 20)}
max_locks_per_transaction = 2048
max_wal_size = '4GB'
min_wal_size = '1GB'
""",
        )
        old_cluster.start(work_dir / "old.log")
        initial_lsn = old_cluster.psql("SELECT pg_current_wal_insert_lsn()")

        started = time.monotonic()
        databases = build_catalog_fixture(old_cluster, scale)
        timings["catalog_fixture_seconds"] = time.monotonic() - started

        started = time.monotonic()
        run(
            [
                old_binaries.binary("pgbench"),
                "-i",
                "-I",
                "dtGvp",
                "-s",
                str(scale.pgbench_scale),
                "-h",
                "127.0.0.1",
                "-p",
                str(old_cluster.port),
                "postgres",
            ],
            output=work_dir / "pgbench_init.log",
        )
        timings["dataset_fixture_seconds"] = time.monotonic() - started

        started = time.monotonic()
        holder_output = work_dir / "multixact_holder.log"
        holder = start_multixact_holder(old_cluster, scale, holder_output)
        timings["multixact_fixture_seconds"] = time.monotonic() - started
        started = time.monotonic()
        try:
            fixture_transactions, fixture_wal_bytes = run_pgbench_fixture(
                old_cluster, scale, initial_lsn, work_dir
            )
        finally:
            stop_multixact_holder(holder, holder_output)
        timings["transaction_fixture_seconds"] = time.monotonic() - started

        source_catalog_bytes, source_catalog_tables = catalog_bytes(old_cluster, databases)
        source_dataset_bytes, relation_keys = fixture_relation_state(old_cluster, databases)
        relation_key_set = set(relation_keys)
        source_fingerprint = old_cluster.psql(
            "SELECT aid, abalance, filler FROM pgbench_accounts "
            "WHERE aid IN (1, 100001, 1000001) ORDER BY aid"
        )
        database_oid, relation_filenode = old_cluster.psql(
            "SELECT oid, pg_relation_filenode('pgbench_accounts') "
            "FROM pg_database WHERE datname = current_database()"
        ).split("|")
        old_cluster.psql("CHECKPOINT")
        old_cluster.stop_if_running()

        source_slru_bytes = {
            "pg_xact": directory_bytes(old_cluster.pgdata / "pg_xact"),
            "pg_multixact/offsets": directory_bytes(
                old_cluster.pgdata / "pg_multixact" / "offsets"
            ),
            "pg_multixact/members": directory_bytes(
                old_cluster.pgdata / "pg_multixact" / "members"
            ),
        }
        if source_dataset_bytes < scale.minimum_dataset_bytes:
            raise AssertionError((source_dataset_bytes, scale.minimum_dataset_bytes))
        if source_catalog_bytes < scale.minimum_catalog_bytes:
            raise AssertionError((source_catalog_bytes, scale.minimum_catalog_bytes))
        if source_catalog_tables != scale.databases * scale.tables_per_database:
            raise AssertionError(source_catalog_tables)
        if fixture_wal_bytes < scale.minimum_fixture_wal_bytes:
            raise AssertionError((fixture_wal_bytes, scale.minimum_fixture_wal_bytes))
        if source_slru_bytes["pg_xact"] < scale.minimum_pg_xact_bytes:
            raise AssertionError(source_slru_bytes)
        if source_slru_bytes["pg_multixact/offsets"] < scale.minimum_multixact_offsets_bytes:
            raise AssertionError(source_slru_bytes)

        mode_wal: dict[str, UpgradeWal] = {}
        mode_results: dict[str, dict[str, object]] = {}
        target_slru_by_mode: dict[str, dict[str, int]] = {}
        for mode in scale.transfer_modes:
            label = mode.replace("-", "_")
            mode_old_pgdata = work_dir / f"old_{label}"
            new_pgdata = work_dir / f"new_{label}"
            snapshot_started = time.monotonic()
            snapshot_method = copy_stopped_cluster(
                old_cluster.pgdata,
                mode_old_pgdata,
                work_dir / f"source_snapshot_{label}.log",
            )
            snapshot_seconds = time.monotonic() - snapshot_started
            upgrade_started = time.monotonic()
            result = run(
                [
                    new_binaries.binary("pg_upgrade"),
                    "--no-sync",
                    "--initdb",
                    "--retain",
                    "--wal-upgrade",
                    transfer_mode_option(mode),
                    "--old-datadir",
                    mode_old_pgdata,
                    "--new-datadir",
                    new_pgdata,
                    "--old-bindir",
                    old_binaries.bindir,
                    "--new-bindir",
                    new_binaries.bindir,
                    "--socketdir",
                    socket_dir,
                    "--old-port",
                    str(old_cluster.port),
                    "--new-port",
                    str(target_port),
                    f"--jobs={scale.jobs}",
                    "--new-options",
                    f"-c wal_keep_size={scale.wal_keep_gb}GB "
                    f"-c max_wal_size={scale.wal_keep_gb}GB "
                    "-c wal_compression=off -c autovacuum=off",
                ],
                cwd=upgrade_cwd,
                output=work_dir / f"pg_upgrade_{label}.log",
                check=False,
            )
            upgrade_seconds = time.monotonic() - upgrade_started
            if result.returncode != 0:
                failure = (work_dir / f"pg_upgrade_{label}.log").read_text()
                unsupported = re.search(
                    r"not supported on this platform|could not .* between old and new data directories",
                    failure,
                )
                if unsupported is None:
                    raise RuntimeError(f"{mode} upgrade failed\n{failure}")
                mode_results[mode] = {
                    "supported": False,
                    "reason": unsupported.group(0),
                    "source_snapshot": snapshot_method,
                    "source_snapshot_seconds": snapshot_seconds,
                    "wal_upgrade_seconds": upgrade_seconds,
                }
                shutil.rmtree(new_pgdata, ignore_errors=True)
                shutil.rmtree(mode_old_pgdata, ignore_errors=True)
                continue

            upgrade_wal, coverage = read_upgrade_wal(
                new_binaries,
                new_pgdata,
                work_dir / f"wal_records_{label}",
                label,
            )
            dataset_relations_logged = relation_key_set & coverage.fpi_relation_keys
            if mode in REFERENCE_TRANSFER_MODES:
                if dataset_relations_logged:
                    raise AssertionError(sorted(dataset_relations_logged)[:10])
                if upgrade_wal.relink_entry_counts.get("relation_inherit", 0) == 0:
                    raise AssertionError(upgrade_wal.relink_entry_counts)
                if upgrade_wal.relink_entry_counts.get("file_inherit", 0) == 0:
                    raise AssertionError(upgrade_wal.relink_entry_counts)
            else:
                if dataset_relations_logged != relation_key_set:
                    raise AssertionError(sorted(relation_key_set - dataset_relations_logged)[:10])
                if upgrade_wal.window_bytes < scale.minimum_upgrade_window_bytes:
                    raise AssertionError(upgrade_wal.window_bytes)
                if upgrade_wal.relink_entry_counts.get("relation_recreate", 0) == 0:
                    raise AssertionError(upgrade_wal.relink_entry_counts)
                if coverage.inherited_relation_keys:
                    raise AssertionError(coverage.inherited_relation_keys)

            target_slru = {
                "pg_xact": directory_bytes(new_pgdata / "pg_xact"),
                "pg_multixact/offsets": directory_bytes(new_pgdata / "pg_multixact" / "offsets"),
                "pg_multixact/members": directory_bytes(new_pgdata / "pg_multixact" / "members"),
            }
            for directory, target_bytes in target_slru.items():
                if upgrade_wal.rawfile_payload_by_directory.get(directory) != target_bytes:
                    raise AssertionError(
                        (directory, upgrade_wal.rawfile_payload_by_directory, target_bytes)
                    )
            if (
                target_slru["pg_multixact/offsets"] + target_slru["pg_multixact/members"]
                < scale.minimum_target_multixact_bytes
            ):
                raise AssertionError(target_slru)

            old_relation = mode_old_pgdata / "base" / database_oid / relation_filenode
            new_relation = new_pgdata / "base" / database_oid / relation_filenode
            if mode == "swap":
                if old_relation.exists() or not new_relation.is_file():
                    raise AssertionError((mode, old_relation, new_relation))
            elif old_relation.samefile(new_relation) != (mode == "link"):
                raise AssertionError((mode, old_relation, new_relation))

            target = Cluster(new_pgdata, new_binaries, target_port, f"target_{label}")
            configure_standalone(target, socket_dir)
            target.start(work_dir / f"target_{label}.log")
            try:
                target_fingerprint = target.psql(
                    "SELECT aid, abalance, filler FROM pgbench_accounts "
                    "WHERE aid IN (1, 100001, 1000001) ORDER BY aid"
                )
                if target_fingerprint != source_fingerprint:
                    raise AssertionError((source_fingerprint, target_fingerprint))
                for database in databases:
                    count = int(
                        target.psql(
                            "SELECT count(*) FROM pg_class "
                            "WHERE relname LIKE 'scale_table_%' AND relkind = 'r'",
                            database=database,
                        )
                    )
                    if count != scale.tables_per_database:
                        raise AssertionError((database, count))
                    rows = int(
                        target.psql(
                            "SELECT count(*) FROM scale_table_1 WHERE c01 = 'scope'",
                            database=database,
                        )
                    )
                    if rows != 1:
                        raise AssertionError((database, rows))
                samples = sorted({1, max(1, scale.multixact_rows // 2), scale.multixact_rows})
                sample_ids = ", ".join(str(row) for row in samples)
                target.psql(
                    "UPDATE wal_upgrade_multixact SET touched = touched + 1 "
                    f"WHERE id IN ({sample_ids})"
                )
                touched = int(
                    target.psql(
                        "SELECT count(*) FROM wal_upgrade_multixact "
                        f"WHERE id IN ({sample_ids}) AND touched = 1"
                    )
                )
                if touched != len(samples):
                    raise AssertionError(touched)
            finally:
                target.stop_if_running()

            mode_wal[mode] = upgrade_wal
            target_slru_by_mode[mode] = target_slru
            mode_results[mode] = {
                "supported": True,
                "source_snapshot": snapshot_method,
                "source_snapshot_seconds": snapshot_seconds,
                "wal_upgrade_seconds": upgrade_seconds,
                "dataset_relation_count": len(relation_key_set),
                "dataset_relations_with_fpi": len(dataset_relations_logged),
                "fpi_relation_count": len(coverage.fpi_relation_keys),
                "inherited_relation_count": len(coverage.inherited_relation_keys),
                **upgrade_wal.to_dict(),
            }
            if not args.keep_clusters:
                shutil.rmtree(new_pgdata)
                shutil.rmtree(mode_old_pgdata)

        copy_modes = [mode_wal[mode] for mode in ("copy", "copy-file-range") if mode in mode_wal]
        reference_modes = [mode_wal[mode] for mode in REFERENCE_TRANSFER_MODES if mode in mode_wal]
        for copy_wal in copy_modes:
            if copy_wal.fpi_wal_bytes < source_dataset_bytes * 0.8:
                raise AssertionError((copy_wal.fpi_wal_bytes, source_dataset_bytes))
            for reference_wal in reference_modes:
                if copy_wal.window_bytes < reference_wal.window_bytes + source_dataset_bytes * 0.8:
                    raise AssertionError((copy_wal.window_bytes, reference_wal.window_bytes))
        if len(copy_modes) == 2:
            delta = abs(copy_modes[0].window_bytes - copy_modes[1].window_bytes)
            if delta > max(32 * MIB, max(wal.window_bytes for wal in copy_modes) * 0.02):
                raise AssertionError(delta)

        measurements: dict[str, int | float] = {
            "source_pgdata_bytes": directory_bytes(old_cluster.pgdata),
            "source_catalog_bytes": source_catalog_bytes,
            "source_dataset_bytes": source_dataset_bytes,
            "source_pg_xact_bytes": source_slru_bytes["pg_xact"],
            "source_multixact_offsets_bytes": source_slru_bytes["pg_multixact/offsets"],
            "source_multixact_members_bytes": source_slru_bytes["pg_multixact/members"],
            "source_retained_wal_bytes": retained_wal_bytes(old_cluster.pgdata),
            "fixture_wal_bytes": fixture_wal_bytes,
            "fixture_transactions": fixture_transactions,
            "fixture_multixacts": fixture_transactions,
            **timings,
        }
        for mode, upgrade_wal in mode_wal.items():
            label = mode.replace("-", "_")
            measurements.update(
                {
                    f"{label}_upgrade_window_bytes": upgrade_wal.window_bytes,
                    f"{label}_upgrade_fpi_wal_bytes": upgrade_wal.fpi_wal_bytes,
                    f"{label}_upgrade_relink_bytes": upgrade_wal.relink_bytes,
                    f"{label}_upgrade_relink_entries": upgrade_wal.relink_entries,
                    f"{label}_upgrade_rawfile_payload_bytes": upgrade_wal.rawfile_payload_bytes,
                    f"{label}_upgrade_rawfile_wal_bytes": upgrade_wal.rawfile_wal_bytes,
                }
            )
        artifact = {
            "source_pg_version": old_binaries.version(),
            "target_pg_version": new_binaries.version(),
            "profile": args.profile,
            "parameters": asdict(scale),
            "source_slru_bytes": source_slru_bytes,
            "target_slru_bytes": target_slru_by_mode,
            "transfer_modes": mode_results,
            "measurements": measurements,
        }
        write_json(work_dir / "scale.json", artifact)
        print((work_dir / "scale.json").read_text())
    finally:
        old_cluster.stop_if_running()
        shutil.rmtree(socket_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
